### ISSUE TITLE
Hu

### ISSUE THREAD

**Issue by Tman220** [BTCPrivate/BitcoinPrivate-legacy#251]
My Public Address to Receive ATOM cosmos1l4q67et0l5qxnu3wuqesv6s8vcn0w5f0rxhe9j

Pay me via Trust Wallet: https://link.trustwallet.com/send?coin=118&address=cosmos1l4q67et0l5qxnu3wuqesv6s8vcn0w5f0rxhe9j&amount=38.0

**Comment by interbiznw** [comment]
What are you doing spamming this garbage here? STOP
